apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: devsecops
build:
  artifacts:
    - image: nginx
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - manifests/deployment.yaml
    - manifests/service.yaml
