apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-cluster
  template:
    metadata:
      labels:
        app: my-cluster
    spec:
      containers:
      - name: my-cluster
        image: gcr.io/valid-song-424717-f0/my-cluster
        ports:
        - containerPort: 3000